[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
releaseCommand = "npx prisma migrate deploy"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
