import fs from 'node:fs';
import path from 'node:path';
import type { RankedItem } from './types.js';
import { learningRepoRoot } from './config.js';
import { appendResearchToNotionPage, updateNotionPageStatus } from './notionClient.js';

function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60);
}

export interface ImplementationOutcome {
  ok: boolean;
  actions: string[];
  error?: string;
}

export async function implementRankedItem(ranked: RankedItem): Promise<ImplementationOutcome> {
  const actions: string[] = [];
  const { item, research, bucket, rankScore, feasibilityScore } = ranked;

  try {
    const docDir = path.join(learningRepoRoot(), 'docs', 'learning-autogen');
    fs.mkdirSync(docDir, { recursive: true });
    const docPath = path.join(docDir, `${slugify(item.title)}.md`);
    const body = [
      `# ${item.title}`,
      '',
      `> Auto-generated by Phase 6 learning loop on ${new Date().toISOString()}`,
      '',
      '## Bucket & scores',
      '',
      `- Bucket: **${bucket}**`,
      `- Rank: **${rankScore}**`,
      `- Feasibility: **${feasibilityScore}**`,
      '',
      '## Research summary',
      '',
      research.summary,
      '',
      '## Codebase signals',
      '',
      ...(research.codebaseHits.length
        ? research.codebaseHits.map(
            (h) => `- \`${h.path}:${h.line}\` — ${h.snippet}`,
          )
        : ['- None matched']),
      '',
      '## Feasibility notes',
      '',
      ...ranked.feasibilityReasons.map((r) => `- ${r}`),
      '',
    ].join('\n');
    fs.writeFileSync(docPath, body, 'utf8');
    actions.push(`wrote ${path.relative(learningRepoRoot(), docPath)}`);

    const notionMd = [
      '### Phase 6 — Research (auto)',
      research.summary,
      '',
      `Bucket: ${bucket} | Rank: ${rankScore} | Feasibility: ${feasibilityScore}`,
    ].join('\n');
    await appendResearchToNotionPage(item.pageId, notionMd);
    actions.push('appended research block to Notion');

    await updateNotionPageStatus(item.pageId, 'In progress');
    actions.push('Notion status → In progress');

    await updateNotionPageStatus(item.pageId, 'Done');
    actions.push('Notion status → Done');

    return { ok: true, actions };
  } catch (err) {
    return { ok: false, actions, error: (err as Error).message };
  }
}
